print('=====DESAFIO 02=====\nPreencha com sua data de nascimento:')
dia = input('Dia: ')
mes = input('Mês: ')
ano = input('Ano: ')
print('Você nasceu no dia {} de {} de {}. Correto?'.format(dia, mes, ano))
